import { Roboto } from "next/font/google";
import "./[locale]/globals.css";
import Header from "./[locale]/client/Header";
import WhatsAppIcon from "./[locale]/_components/WhatsAppIcon";
import Footer from "./[locale]/_components/Footer";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Top-Notch Patient Experience in Turkiye",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Meta Pixel Code */}
       <script
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '1568356953733232');
              fbq('track', 'PageView');
            `,
          }}
        />
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: 'none' }}
            src="https://www.facebook.com/tr?id=1568356953733232&ev=PageView&noscript=1"
          />
        </noscript>
      {/* End Meta Pixel Code */}
      {/* Google Tag (gtag.js) */}
      <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-GTW475WFDN"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-GTW475WFDN');
            `,
          }}
        />
        {/* Google Tag Manager */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){
                w[l]=w[l]||[];
                w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});
                var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
                j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;
                f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-5DBZV493');
            `,
          }}
        />
      </head>
      <body className={roboto.className}>
         {/* Google Tag Manager (noscript) */}
         <noscript>
            <iframe
              src="https://www.googletagmanager.com/ns.html?id=GTM-5DBZV493"
              height="0"
              width="0"
              style={{ display: 'none', visibility: 'hidden' }}
            ></iframe>
          </noscript>
        <Header />
        {children}
        <WhatsAppIcon />
        <Footer />
      </body>
    </html>
  );
}
